### ISSUE TITLE
Vulnix fails because feed data is not found

### ISSUE THREAD

**Issue by matthiasdotsh** [nix-community/vulnix#93]
Hi all,

since yesterday `vulnix` is no longer working on my systems:

```nix
$ vulnix -R /nix/store/*.drv
Traceback (most recent call last):
  File "/nix/store/rygfmwj1yvzx6ndfc33j5ajwqfp7408d-vulnix-1.10.1/bin/.vulnix-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/wazkvq0fsirz6ng9g5sjmr93mh159g64-python3.10-click-8.1.6/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/wazkvq0fsirz6ng9g5sjmr93mh159g64-python3.10-click-8.1.6/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nix/store/wazkvq0fsirz6ng9g5sjmr93mh159g64-python3.10-click-8.1.6/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/wazkvq0fsirz6ng9g5sjmr93mh159g64-python3.10-click-8.1.6/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/rygfmwj1yvzx6ndfc33j5ajwqfp7408d-vulnix-1.10.1/lib/python3.10/site-packages/vulnix/main.py", line 153, in main
    nvd.update()
  File "/nix/store/rygfmwj1yvzx6ndfc33j5ajwqfp7408d-vulnix-1.10.1/lib/python3.10/site-packages/vulnix/nvd.py", line 119, in update
    changed.append(arch.download(self.mirror, self.meta))
  File "/nix/store/rygfmwj1yvzx6ndfc33j5ajwqfp7408d-vulnix-1.10.1/lib/python3.10/site-packages/vulnix/nvd.py", line 187, in download
    r.raise_for_status()
  File "/nix/store/pkzm1x5xkn6y7cf6pw17d101l1z64ffs-python3.10-requests-2.31.0/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.json.gz
```

From my logs I can say that it worked until march10th and failed from march 11th with the above mentioned error.

**Comment by matthiasdotsh** [comment]
I suspect that this is due to changes to the API of nvd.nist.gov:

https://nvd.nist.gov/general/news/change-timeline
> All new users, as well as existing users whose workflows include web scraping tools, the legacy data feeds, or the 1.0 APIs, must transition to the 2.0 APIs to continue to get NVD data without interruption. 

[Your guide to moving from API 1.0 to API 2.0](https://nvd.nist.gov/general/news/api-20-announcements)

**Comment by matthiasdotsh** [comment]
I can no longer reproduce it
